# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_course_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resourcesCascade
from course_manager import CourseManager 
from PyQt5.QtCore import pyqtSignal, QObject
import mysql.connector

class Ui_add_course_settings(object):

    def setupUi(self, add_course_settings):
        add_course_settings.setObjectName("add_course_settings")
        add_course_settings.resize(579, 687)
        add_course_settings.setStyleSheet("background-color: rgb(56, 49, 117);")
        self.centralwidget = QtWidgets.QWidget(add_course_settings)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1221, 801))
        self.bg.setStyleSheet("")
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap(":/images/images for cascade/bg_image.png"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.add_course_title = QtWidgets.QLabel(self.centralwidget)
        self.add_course_title.setGeometry(QtCore.QRect(250, 0, 311, 61))
        self.add_course_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_course_title.setStyleSheet("background: transparent;\n"
"font: 25pt \"Montserrat\";\n"
"font-weight: bold;\n"
"color: rgb(167, 145, 203);\n"
"qproperty-alignment: AlignRight;\n"
"")
        self.add_course_title.setObjectName("add_course_title")
        self.nav_line = QtWidgets.QLabel(self.centralwidget)
        self.nav_line.setGeometry(QtCore.QRect(240, 55, 321, 1))
        self.nav_line.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop:0 rgba(255, 255, 255, 0),\n"
"    stop:1 rgba(255, 255, 255, 200));")
        self.nav_line.setText("")
        self.nav_line.setObjectName("nav_line")
        self.course_title = QtWidgets.QLabel(self.centralwidget)
        self.course_title.setGeometry(QtCore.QRect(20, 80, 321, 31))
        self.course_title.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 15pt \"Montserrat\";\n"
"color: rgb(167, 145, 203);")
        self.course_title.setObjectName("course_title")
        self.course_title_input = QtWidgets.QTextEdit(self.centralwidget)
        self.course_title_input.setGeometry(QtCore.QRect(30, 120, 511, 41))
        self.course_title_input.setStyleSheet("background-color: rgb(149, 145, 203,0.4);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(255, 255, 255);")
        self.course_title_input.setObjectName("course_title_input")
        self.syllabus_title = QtWidgets.QLabel(self.centralwidget)
        self.syllabus_title.setGeometry(QtCore.QRect(20, 190, 321, 31))
        self.syllabus_title.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 15pt \"Montserrat\";\n"
"color: rgb(167, 145, 203);")
        self.syllabus_title.setObjectName("syllabus_title")
        self.syllabus_title_input = QtWidgets.QTextEdit(self.centralwidget)
        self.syllabus_title_input.setGeometry(QtCore.QRect(30, 230, 511, 151))
        self.syllabus_title_input.setStyleSheet("background-color: rgb(149, 145, 203,0.4);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(255, 255, 255);")
        self.syllabus_title_input.setObjectName("syllabus_title_input")
        self.modules_title = QtWidgets.QLabel(self.centralwidget)
        self.modules_title.setGeometry(QtCore.QRect(20, 400, 321, 31))
        self.modules_title.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 15pt \"Montserrat\";\n"
"color: rgb(167, 145, 203);")
        self.modules_title.setObjectName("modules_title")
        self.ModuleWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.ModuleWidget.setGeometry(QtCore.QRect(30, 440, 511, 171))
        self.ModuleWidget.setStyleSheet("font: 9pt \"Monteserrat\";\n"
"color: rgb(255, 255, 255);")
        self.ModuleWidget.setObjectName("ModuleWidget")
        self.mod1 = QtWidgets.QWidget()
        self.mod1.setObjectName("mod1")
        self.syllabus_title_input_1 = QtWidgets.QTextEdit(self.mod1)
        self.syllabus_title_input_1.setGeometry(QtCore.QRect(0, 0, 511, 151))
        self.syllabus_title_input_1.setStyleSheet("background-color: rgb(149, 145, 203,0.4);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(255, 255, 255);")
        self.syllabus_title_input_1.setReadOnly(True)
        self.syllabus_title_input_1.setPlaceholderText("")
        self.syllabus_title_input_1.setObjectName("syllabus_title_input_1")
        self.ModuleWidget.addTab(self.mod1, "")
        self.mod2 = QtWidgets.QWidget()
        self.mod2.setObjectName("mod2")
        self.syllabus_title_input_2 = QtWidgets.QTextEdit(self.mod2)
        self.syllabus_title_input_2.setGeometry(QtCore.QRect(0, 0, 511, 151))
        self.syllabus_title_input_2.setStyleSheet("background-color: rgb(149, 145, 203,0.4);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(255, 255, 255);")
        self.syllabus_title_input_2.setReadOnly(True)
        self.syllabus_title_input_2.setPlaceholderText("")
        self.syllabus_title_input_2.setObjectName("syllabus_title_input_2")
        self.ModuleWidget.addTab(self.mod2, "")
        self.mod3 = QtWidgets.QWidget()
        self.mod3.setObjectName("mod3")
        self.syllabus_title_input_3 = QtWidgets.QTextEdit(self.mod3)
        self.syllabus_title_input_3.setGeometry(QtCore.QRect(0, 0, 511, 151))
        self.syllabus_title_input_3.setStyleSheet("background-color: rgb(149, 145, 203,0.4);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(255, 255, 255);")
        self.syllabus_title_input_3.setReadOnly(True)
        self.syllabus_title_input_3.setPlaceholderText("")
        self.syllabus_title_input_3.setObjectName("syllabus_title_input_3")
        self.ModuleWidget.addTab(self.mod3, "")
        self.mod4 = QtWidgets.QWidget()
        self.mod4.setObjectName("mod4")
        self.syllabus_title_input_4 = QtWidgets.QTextEdit(self.mod4)
        self.syllabus_title_input_4.setGeometry(QtCore.QRect(0, 0, 511, 151))
        self.syllabus_title_input_4.setStyleSheet("background-color: rgb(149, 145, 203,0.4);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(255, 255, 255);")
        self.syllabus_title_input_4.setReadOnly(True)
        self.syllabus_title_input_4.setPlaceholderText("")
        self.syllabus_title_input_4.setObjectName("syllabus_title_input_4")
        self.ModuleWidget.addTab(self.mod4, "")
        self.mod5 = QtWidgets.QWidget()
        self.mod5.setObjectName("mod5")
        self.syllabus_title_input_5 = QtWidgets.QTextEdit(self.mod5)
        self.syllabus_title_input_5.setGeometry(QtCore.QRect(0, 0, 511, 151))
        self.syllabus_title_input_5.setStyleSheet("background-color: rgb(149, 145, 203,0.4);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(255, 255, 255);")
        self.syllabus_title_input_5.setReadOnly(True)
        self.syllabus_title_input_5.setPlaceholderText("")
        self.syllabus_title_input_5.setObjectName("syllabus_title_input_5")
        self.ModuleWidget.addTab(self.mod5, "")
        self.enter_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter_button.setGeometry(QtCore.QRect(450, 390, 93, 28))
        self.enter_button.setStyleSheet("QPushButton {\n"
"    background-color: rgba(185, 185, 185, 0);\n"
"    font: 10pt \"Montserrat\";\n"
"    color: rgb(154, 154, 154);\n"
"    border-radius: 5px;\n"
"   \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(195, 195, 195);\n"
"}\n"
"")
        self.enter_button.setObjectName("enter_button")
        self.enter_button.clicked.connect(self.handle_user_input)

        self.enter2_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter2_button.setGeometry(QtCore.QRect(450, 630, 93, 28))
        self.enter2_button.setStyleSheet("QPushButton {\n"
"    background-color: rgba(185, 185, 185, 0);\n"
"    font: 10pt \"Montserrat\";\n"
"    color: rgb(154, 154, 154);\n"
"    border-radius: 5px;\n"
"   \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(195, 195, 195);\n"
"}\n"
"")
        self.enter2_button.setObjectName("enter2_button")
        self.enter2_button.clicked.connect(self.on_click)
        
        add_course_settings.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(add_course_settings)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 579, 26))
        self.menubar.setObjectName("menubar")
        add_course_settings.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(add_course_settings)
        self.statusbar.setObjectName("statusbar")
        add_course_settings.setStatusBar(self.statusbar)

        self.retranslateUi(add_course_settings)
        self.ModuleWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(add_course_settings)
    
    def retranslateUi(self, add_course_settings):
        _translate = QtCore.QCoreApplication.translate
        add_course_settings.setWindowTitle(_translate("add_course_settings", "MainWindow"))
        self.add_course_title.setText(_translate("add_course_settings", "Add Course"))
        self.course_title.setText(_translate("add_course_settings", "Title"))
        self.course_title_input.setPlaceholderText(_translate("add_course_settings", "Enter course title here..."))
        self.syllabus_title.setText(_translate("add_course_settings", "Syllabus"))
        self.syllabus_title_input.setPlaceholderText(_translate("add_course_settings", "Enter syllabus here..."))
        self.modules_title.setText(_translate("add_course_settings", "Modules"))
        self.ModuleWidget.setTabText(self.ModuleWidget.indexOf(self.mod1), _translate("add_course_settings", "Module 1"))
        self.ModuleWidget.setTabText(self.ModuleWidget.indexOf(self.mod2), _translate("add_course_settings", "Module 2"))
        self.ModuleWidget.setTabText(self.ModuleWidget.indexOf(self.mod3), _translate("add_course_settings", "Module 3"))
        self.ModuleWidget.setTabText(self.ModuleWidget.indexOf(self.mod4), _translate("add_course_settings", "Module 4"))
        self.ModuleWidget.setTabText(self.ModuleWidget.indexOf(self.mod5), _translate("add_course_settings", "Module 5"))
        self.enter_button.setText(_translate("add_course_settings", "Modularise"))
        self.enter2_button.setText(_translate("add_course_settings", "Enter"))

    def on_click(self):
        course_title = self.course_title_input.toPlainText()
        syllabus_content = self.syllabus_title_input.toPlainText()

        conn = mysql.connector.connect(
        host = "localhost",
        user = "root",
        password = "kuhu2004",
        database = "cascade_project"
        )
        cursor = conn.cursor()
        query = "INSERT INTO courses (name, syllabus) VALUES (%s, %s)"
        values = (course_title, syllabus_content)
        cursor.execute(query, values)
        conn.commit()
        
        cursor.close()
        conn.close()

    def __init__(self):
        self.course_manager = CourseManager()
        
    def handle_user_input(self):
        # Retrieve the user input (title and syllabus)
        title = self.course_title_input.toPlainText()  # Replace with your actual input widget
        syllabus = self.syllabus_title_input.toPlainText()  # Replace with your actual input widget

        # Set the course data and update the modules
        self.course_manager.set_course(title, syllabus)
        self.update_modules()


    def update_modules(self):
        # Split the syllabus into chunks of one line
        course_syllabus = self.course_manager.get_course_syllabus()
        syllabus_lines = course_syllabus.split("*")
        num_modules = min(len(syllabus_lines), 5)  # Limit to 5 modules

        for i in range(num_modules):
            module_text = syllabus_lines[i]  # Use one line at a time
            module_widget = getattr(self, f"syllabus_title_input_{i + 1}")  # Get the mod widget dynamically
            module_widget.setPlainText(module_text)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_course_settings = QtWidgets.QMainWindow()
    ui = Ui_add_course_settings()
    ui.setupUi(add_course_settings)
    add_course_settings.show()
    sys.exit(app.exec_())
