# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QVBoxLayout
from PyQt5.QtWidgets import QLabel, QDialog
import resourcesCascade
from todo_manager import TodoManager
from newtimer_sql import Ui_Timer
from notesfinal import Ui_MainWindow
from settings import Ui_settings
from flashcard3 import Flashcard
from PyQt5.QtCore import Qt
from music_player_final import MusicPlayer
from study_plan import Ui_study_plan
from statistics_1 import Ui_Statistics
import mysql
from mysql.connector import Error

class Ui_mainpage(object):
    def openNotesViewer(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openSettings(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_settings()
        self.ui.setupUi(self.window)
        self.window.show()

    def openStatistics(self):
        self.window = QtWidgets.QMainWindow()
        self.window.show()

    def openFlashcards(self, event):
        if event.button() == Qt.LeftButton:  # Handle left mouse button click
            self.flashcard_window = QtWidgets.QMainWindow()
            self.flashcard_ui = Flashcard()  # Create an instance of your Flashcard widget
            self.flashcard_window.setCentralWidget(self.flashcard_ui)  # Set the widget as central
            self.flashcard_window.show()

    def start_music_player(self):
        self.music_player = MusicPlayer()
        self.music_player.show()

    def setupUi(self, mainpage):
        mainpage.setObjectName("mainpage")
        mainpage.resize(1211, 814)
        mainpage.setStyleSheet("background-color: rgb(37, 60, 105);")
        self.centralwidget = QtWidgets.QWidget(mainpage)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(-7, -10, 1221, 801))
        self.bg.setText("")
        self.bg.setPixmap(QPixmap(":/images/images for cascade/bg_image.png"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.logo_bg_shadow = QtWidgets.QLabel(self.centralwidget)
        self.logo_bg_shadow.setGeometry(QtCore.QRect(25, 25, 61, 61))
        self.logo_bg_shadow.setStyleSheet("background-color: rgb(23, 35, 67);\n"
"border-radius: 10px;\n"
"")
        self.logo_bg_shadow.setText("")
        self.logo_bg_shadow.setObjectName("logo_bg_shadow")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 20, 61, 61))
        self.logo.setStyleSheet("background-color: rgb(99, 106, 154);\n"
"border-radius: 10px;\n"
"padding: 5px;\n"
"box-shadow: 10px 10px 5px rgba(0, 0, 0, 1);")
        self.logo.setText("")
        self.logo.setPixmap(QPixmap(":/images/images for cascade/Cascade-removebg-preview.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.nav_line = QtWidgets.QLabel(self.centralwidget)
        self.nav_line.setGeometry(QtCore.QRect(550, 60, 551, 1))
        self.nav_line.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.nav_line.setText("")
        self.nav_line.setObjectName("nav_line")
        self.intro_nav = QtWidgets.QLabel(self.centralwidget)
        self.intro_nav.setGeometry(QtCore.QRect(570, 20, 101, 41))
        self.intro_nav.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Montserrat\";")
        self.intro_nav.setObjectName("intro_nav")
        self.studyplan_nav = QtWidgets.QLabel(self.centralwidget)
        self.studyplan_nav.setGeometry(QtCore.QRect(680, 20, 81, 41))
        self.studyplan_nav.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Montserrat\";")
        self.studyplan_nav.setObjectName("studyplan_nav")
        self.studyplan_nav.mousePressEvent = lambda event: self.openStudyPlan()
        self.calender_nav = QtWidgets.QLabel(self.centralwidget)
        self.calender_nav.setGeometry(QtCore.QRect(770, 20, 71, 41))
        self.calender_nav.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Montserrat\";")
        self.calender_nav.setObjectName("calender_nav")
        self.stats_nav = QtWidgets.QLabel(self.centralwidget)
        self.stats_nav.setGeometry(QtCore.QRect(850, 20, 61, 41))
        self.stats_nav.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Montserrat\";")
        self.stats_nav.setObjectName("stats_nav")
        self.stats_nav.mousePressEvent = lambda event: self.openStatistics()
        self.faq_nav = QtWidgets.QLabel(self.centralwidget)
        self.faq_nav.setGeometry(QtCore.QRect(930, 20, 41, 41))
        self.faq_nav.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Montserrat\";")
        self.faq_nav.setObjectName("faq_nav")
        self.about_nav = QtWidgets.QLabel(self.centralwidget)
        self.about_nav.setGeometry(QtCore.QRect(990, 20, 41, 41))
        self.about_nav.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Montserrat\";")
        self.about_nav.setObjectName("about_nav")
        self.contact_nav = QtWidgets.QLabel(self.centralwidget)
        self.contact_nav.setGeometry(QtCore.QRect(1050, 20, 51, 41))
        self.contact_nav.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"Montserrat\";")
        self.contact_nav.setObjectName("contact_nav")
        self.settings = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openSettings())
        self.settings.setGeometry(QtCore.QRect(1120, 30, 31, 28))
        self.settings.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 14px;")
        
        self.settings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QPixmap(":/images/images for cascade/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon)
        self.settings.setObjectName("settings")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(1160, 30, 31, 28))
        self.help.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 14px;")
        self.help.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QPixmap(":/images/images for cascade/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help.setIcon(icon1)
        self.help.setObjectName("help")
        self.help.clicked.connect(self.start_music_player)
        self.music = QtWidgets.QPushButton(self.centralwidget)
        self.music.setGeometry(QtCore.QRect(1160, 70, 31, 28))
        self.music.setStyleSheet("background-color: rgb(0,0,0);\n"
"border-radius: 14px;")
        self.music.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QPixmap(":/images/images for cascade/icon-musical-notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.music.setIcon(icon5)
        self.music.setIconSize(QtCore.QSize(40, 40))  
        self.music.setObjectName("music")
        self.music.clicked.connect(self.start_music_player)
        self.sidebar = QtWidgets.QLabel(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(-10, 170, 71, 451))
        self.sidebar.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(167, 145, 203,0.3);")
        self.sidebar.setText("")
        self.sidebar.setObjectName("sidebar")

        self.timer = QtWidgets.QLabel(self.centralwidget)
        self.timer.setGeometry(QtCore.QRect(10, 180, 41, 51))
        self.timer.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.timer.setText("")
        self.timer.setPixmap(QPixmap(":/images/images for cascade/timer_icon.png"))
        self.timer.setObjectName("timer")
        self.timer.mousePressEvent = lambda event: self.timer_clicked(event)

        self.daily_schedule = QtWidgets.QLabel(self.centralwidget)
        self.daily_schedule.setGeometry(QtCore.QRect(13, 309, 41, 51))
        self.daily_schedule.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.daily_schedule.setText("")
        self.daily_schedule.setPixmap(QPixmap(":/images/images for cascade/dailyScedule_icon.png"))
        self.daily_schedule.setObjectName("daily_schedule")
        self.flashcard = QtWidgets.QLabel(self.centralwidget)
        self.flashcard.setGeometry(QtCore.QRect(10, 245, 41, 51))
        self.flashcard.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.flashcard.setText("")
        self.flashcard.setPixmap(QPixmap(":/images/images for cascade/flashcard_icon.png"))
        self.flashcard.setObjectName("flashcard")
        self.flashcard.mousePressEvent = self.openFlashcards

        self.quiz = QtWidgets.QLabel(self.centralwidget)
        self.quiz.setGeometry(QtCore.QRect(17, 440, 41, 41))
        self.quiz.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.quiz.setText("")
        self.quiz.setPixmap(QPixmap(":/images/images for cascade/Quiz_icon.png"))
        self.quiz.setScaledContents(False)
        self.quiz.setObjectName("quiz")
        self.sylabus_tracker = QtWidgets.QLabel(self.centralwidget)
        self.sylabus_tracker.setGeometry(QtCore.QRect(12, 374, 41, 51))
        self.sylabus_tracker.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.sylabus_tracker.setText("")
        self.sylabus_tracker.setPixmap(QPixmap(":/images/images for cascade/SyllabusTracker_icon.png"))
        self.sylabus_tracker.setObjectName("sylabus_tracker")
        self.feedback = QtWidgets.QLabel(self.centralwidget)
        self.feedback.setGeometry(QtCore.QRect(10, 563, 41, 51))
        self.feedback.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.feedback.setText("")
        self.feedback.setPixmap(QPixmap(":/images/images for cascade/feedback_icon.png"))
        self.feedback.setObjectName("feedback")
        self.sidebar_line_2 = QtWidgets.QLabel(self.centralwidget)
        self.sidebar_line_2.setGeometry(QtCore.QRect(10, 235, 41, 1))
        self.sidebar_line_2.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.sidebar_line_2.setText("")
        self.sidebar_line_2.setObjectName("sidebar_line_2")
        self.sidebar_line_3 = QtWidgets.QLabel(self.centralwidget)
        self.sidebar_line_3.setGeometry(QtCore.QRect(10, 298, 41, 1))
        self.sidebar_line_3.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.sidebar_line_3.setText("")
        self.sidebar_line_3.setObjectName("sidebar_line_3")
        self.sidebar_line_4 = QtWidgets.QLabel(self.centralwidget)
        self.sidebar_line_4.setGeometry(QtCore.QRect(10, 360, 41, 1))
        self.sidebar_line_4.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.sidebar_line_4.setText("")
        self.sidebar_line_4.setObjectName("sidebar_line_4")
        self.sidebar_line_5 = QtWidgets.QLabel(self.centralwidget)
        self.sidebar_line_5.setGeometry(QtCore.QRect(10, 427, 41, 1))
        self.sidebar_line_5.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.sidebar_line_5.setText("")
        self.sidebar_line_5.setObjectName("sidebar_line_5")
        self.sidebar_line_6 = QtWidgets.QLabel(self.centralwidget)
        self.sidebar_line_6.setGeometry(QtCore.QRect(10, 490, 41, 1))
        self.sidebar_line_6.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.sidebar_line_6.setText("")
        self.sidebar_line_6.setObjectName("sidebar_line_6")
        self.stars = QtWidgets.QLabel(self.centralwidget)
        self.stars.setGeometry(QtCore.QRect(280, 120, 111, 111))
        self.stars.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.stars.setText("")
        self.stars.setPixmap(QPixmap(":/images/images for cascade/starsss.png"))
        self.stars.setObjectName("stars")
        self.main_box = QtWidgets.QLabel(self.centralwidget)
        self.main_box.setGeometry(QtCore.QRect(630, 150, 521, 591))
        self.main_box.setStyleSheet("border-top-right-radius: 13px;\n"
"border-bottom-right-radius: 13px;\n"
"background-color: rgb(167, 145, 203,0.2);")
        self.main_box.setText("")
        self.main_box.setObjectName("main_box")
        self.main_box_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_box_2.setGeometry(QtCore.QRect(660, 180, 461, 531))
        self.main_box_2.setStyleSheet("border-top-right-radius: 13px;\n"
"border-bottom-right-radius: 13px;\n"
"background-color: rgb(0, 0, 0,0.6);")
        self.main_box_2.setText("")
        self.main_box_2.setObjectName("main_box_2")
        self.quick_notes_title = QtWidgets.QLabel(self.centralwidget)
        self.quick_notes_title.setGeometry(QtCore.QRect(970, 188, 201, 71))
        self.quick_notes_title.setStyleSheet("color: rgb(167, 145, 203);\n"
"background-color: rgb(255, 255, 255,0);\n"
"font: 25pt \"Montserrat\";\n"
"")
        self.quick_notes_title.setObjectName("quick_notes_title")
        self.todo_title = QtWidgets.QLabel(self.centralwidget)
        self.todo_title.setGeometry(QtCore.QRect(980, 440, 201, 71))
        self.todo_title.setStyleSheet("color: rgb(167, 145, 203);\n"
"background-color: rgb(255, 255, 255,0);\n"
"font: 25pt \"Montserrat\";\n"
"")
        self.todo_title.setObjectName("todo_title")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(690, 530, 381, 31))
        self.checkBox.setStyleSheet("QCheckBox {\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"    font: 12pt \"Montserrat\";\n"
"    color: rgb(195, 195, 195);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #c3c3c3;\n"
"    background: none;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #c3c3c3;\n"
"    background-color: rgb(0,0,0,0);\n"
"    border-radius: 5px;\n"
"    image: url(:/images/images for cascade/checkmark.png);\n"
"}\n"
"\n"
"")
    
        self.checkBox.setText("")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(690, 560, 391, 42))
        self.checkBox_2.setStyleSheet("QCheckBox {\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"    font: 12pt \"Montserrat\";\n"
"    color: rgb(195, 195, 195);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #c3c3c3;\n"
"    background: none;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #c3c3c3;\n"
"    background-color: rgb(0,0,0,0);\n"
"    border-radius: 5px;\n"
"    image: url(:/images/images for cascade/checkmark.png);\n"
"}\n"
"\n"
"")
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(690, 601, 391, 31))
        self.checkBox_3.setStyleSheet("QCheckBox {\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"    font: 12pt \"Montserrat\";\n"
"    color: rgb(195, 195, 195);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #c3c3c3;\n"
"    background: none;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #c3c3c3;\n"
"    background-color: rgb(0,0,0,0);\n"
"    border-radius: 5px;\n"
"    image: url(:/images/images for cascade/checkmark.png);\n"
"}\n"
"\n"
"")
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(690, 640, 391, 31))
        self.checkBox_4.setStyleSheet("QCheckBox {\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"    font: 12pt \"Montserrat\";\n"
"    color: rgb(195, 195, 195);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #c3c3c3;\n"
"    background: none;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #c3c3c3;\n"
"    background-color: rgb(0,0,0,0);\n"
"    border-radius: 5px;\n"
"    image: url(:/images/images for cascade/checkmark.png);\n"
"}\n"
"\n"
"")
            
        self.todo_line = QtWidgets.QLabel(self.centralwidget)
        self.todo_line.setGeometry(QtCore.QRect(720, 554, 371, 1))
        self.todo_line.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.todo_line.setText("")
        self.todo_line.setObjectName("todo_line")
        self.todo_line_2 = QtWidgets.QLabel(self.centralwidget)
        self.todo_line_2.setGeometry(QtCore.QRect(720, 593, 370, 1))
        self.todo_line_2.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.todo_line_2.setText("")
        self.todo_line_2.setObjectName("todo_line_2")
        self.todo_line_3 = QtWidgets.QLabel(self.centralwidget)
        self.todo_line_3.setGeometry(QtCore.QRect(720, 627, 370, 1))
        self.todo_line_3.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.todo_line_3.setText("")
        self.todo_line_3.setObjectName("todo_line_3")
        self.todo_line_4 = QtWidgets.QLabel(self.centralwidget)
        self.todo_line_4.setGeometry(QtCore.QRect(720, 665, 370, 1))
        self.todo_line_4.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.todo_line_4.setText("")
        self.todo_line_4.setObjectName("todo_line_4")
        self.todo = QtWidgets.QTextEdit(self.centralwidget)
        self.todo.setGeometry(QtCore.QRect(730, 530, 361, 21))
        self.todo.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(195, 195, 195);")
        self.todo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.todo.setPlaceholderText("")
        self.todo.setObjectName("todo")
        self.todo_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.todo_2.setGeometry(QtCore.QRect(730, 570, 361, 21))
        self.todo_2.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(195, 195, 195);")
        self.todo_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.todo_2.setObjectName("todo_2")
        self.todo_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.todo_3.setGeometry(QtCore.QRect(730, 604, 361, 21))
        self.todo_3.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(195, 195, 195);")
        self.todo_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.todo_3.setObjectName("todo_3")
        self.todo_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.todo_4.setGeometry(QtCore.QRect(730, 640, 361, 21))
        self.todo_4.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(195, 195, 195);")
        self.todo_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.todo_4.setObjectName("todo_4")

        checkboxes = [self.checkBox, self.checkBox_2, self.checkBox_3, self.checkBox_4]
        todos = [self.todo, self.todo_2, self.todo_3, self.todo_4]

        todo_manager = TodoManager(checkboxes, todos)    
        
        self.notes_line = QtWidgets.QLabel(self.centralwidget)
        self.notes_line.setGeometry(QtCore.QRect(690, 295, 401, 1))
        self.notes_line.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.notes_line.setText("")
        self.notes_line.setObjectName("notes_line")
        self.sidebar_line_7 = QtWidgets.QLabel(self.centralwidget)
        self.sidebar_line_7.setGeometry(QtCore.QRect(10, 552, 41, 1))
        self.sidebar_line_7.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.sidebar_line_7.setText("")
        self.sidebar_line_7.setObjectName("sidebar_line_7")
        self.notes = QtWidgets.QLabel(self.centralwidget)
        self.notes.setGeometry(QtCore.QRect(9, 500, 41, 51))
        self.notes.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.notes.setText("")
        self.notes.setPixmap(QPixmap(":/images/images for cascade/notes_icon.png"))
        self.notes.setObjectName("notes")
        self.notes_line_2 = QtWidgets.QLabel(self.centralwidget)
        self.notes_line_2.setGeometry(QtCore.QRect(690, 330, 401, 1))
        self.notes_line_2.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.notes_line_2.setText("")
        self.notes_line_2.setObjectName("notes_line_2")
        self.notes_line_3 = QtWidgets.QLabel(self.centralwidget)
        self.notes_line_3.setGeometry(QtCore.QRect(690, 365, 401, 1))
        self.notes_line_3.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.notes_line_3.setText("")
        self.notes_line_3.setObjectName("notes_line_3")
        self.notes_line_4 = QtWidgets.QLabel(self.centralwidget)
        self.notes_line_4.setGeometry(QtCore.QRect(690, 400, 401, 1))
        self.notes_line_4.setStyleSheet("background-color: rgb(255, 255, 255,0.5);")
        self.notes_line_4.setText("")
        self.notes_line_4.setObjectName("notes_line_4")
        self.welcome_title = QtWidgets.QLabel(self.centralwidget)
        self.welcome_title.setGeometry(QtCore.QRect(230, 210, 211, 81))
        self.welcome_title.setStyleSheet("color: rgb(167, 145, 203);\n"
"background-color: rgb(255, 255, 255,0);\n"
"font: 25pt \"Montserrat\";\n"
"font-weight: bold;")
        self.welcome_title.setObjectName("welcome_title")
        self.note_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.note_1.setGeometry(QtCore.QRect(690, 270, 221, 31))
        self.note_1.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(195, 195, 195);")
        self.note_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.note_1.setObjectName("note_1")
        self.note_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.note_2.setGeometry(QtCore.QRect(690, 305, 221, 31))
        self.note_2.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(195, 195, 195);")
        self.note_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.note_2.setObjectName("note_2")
        self.note_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.note_3.setGeometry(QtCore.QRect(690, 340, 221, 31))
        self.note_3.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(195, 195, 195);")
        self.note_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.note_3.setObjectName("note_3")
        self.note_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.note_4.setGeometry(QtCore.QRect(690, 375, 221, 31))
        self.note_4.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 10pt \"Monteserrat\";\n"
"color: rgb(195, 195, 195);")
        self.note_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.note_4.setObjectName("note_4")
        self.last_update_1 = QtWidgets.QLabel(self.centralwidget)
        self.last_update_1.setGeometry(QtCore.QRect(990, 270, 101, 20))
        self.last_update_1.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 6pt \"Montserrat\";\n"
"color: rgb(195, 195, 195);")
        self.last_update_1.setObjectName("last_update_1")
        self.last_update_2 = QtWidgets.QLabel(self.centralwidget)
        self.last_update_2.setGeometry(QtCore.QRect(990, 305, 101, 20))
        self.last_update_2.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 6pt \"Montserrat\";\n"
"color: rgb(195, 195, 195);")
        self.last_update_2.setObjectName("last_update_2")
        self.last_update_3 = QtWidgets.QLabel(self.centralwidget)
        self.last_update_3.setGeometry(QtCore.QRect(990, 340, 101, 20))
        self.last_update_3.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 6pt \"Montserrat\";\n"
"color: rgb(195, 195, 195);")
        self.last_update_3.setObjectName("last_update_3")
        self.last_update_4 = QtWidgets.QLabel(self.centralwidget)
        self.last_update_4.setGeometry(QtCore.QRect(990, 375, 101, 20))
        self.last_update_4.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"font: 6pt \"Montserrat\";\n"
"color: rgb(195, 195, 195);")
        self.view_more_notes = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openNotesViewer())
        self.view_more_notes.setGeometry(QtCore.QRect(1010, 410, 93, 28))
        self.view_more_notes.setStyleSheet("QPushButton {\n"
"    background-color: rgba(185, 185, 185, 0);\n"
"    font: 8pt \"Montserrat\";\n"
"    color: rgb(154, 154, 154);\n"
"    border-radius: 5px;\n"
"   \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(195, 195, 195);\n"
"}\n"
"")
        self.view_more_notes.setObjectName("view_more_notes")
        self.last_update_4.setObjectName("last_update_4")
        self.ai_chat = QtWidgets.QTextEdit(self.centralwidget)
        self.ai_chat.setGeometry(QtCore.QRect(110, 290, 461, 290))
        self.ai_chat.setStyleSheet("border-radius: 13px;\n"
"background-color: rgb(0, 0, 0,0.5);")
        self.ai_chat.setText("")
        self.ai_chat.setObjectName("ai_chat")
        self.ai_chat_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ai_chat_input.setGeometry(QtCore.QRect(110, 588, 463, 35))
        self.ai_chat_input.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
        "font: 10pt 'Montserrat';\n"
        "color: rgb(195, 195, 195);\n"
        "border: 1px solid #d4b9e9;\n"
        "border-radius: 6px;")
        self.ai_chat_input.setFrame(False)
        self.ai_chat_input.setObjectName("ai_chat_input")

        self.ai_chat_enter = QtWidgets.QPushButton(self.centralwidget)
        self.ai_chat_enter.setGeometry(QtCore.QRect(540, 590, 41, 31))
        self.ai_chat_enter.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.ai_chat_enter.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QPixmap(":/images/images for cascade/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ai_chat_enter.setIcon(icon2)
        self.ai_chat_enter.setObjectName("ai_chat_enter")
        mainpage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainpage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1211, 26))
        self.menubar.setObjectName("menubar")
        mainpage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainpage)
        self.statusbar.setObjectName("statusbar")
        mainpage.setStatusBar(self.statusbar)

        self.retranslateUi(mainpage)
        QtCore.QMetaObject.connectSlotsByName(mainpage)

    def retranslateUi(self, mainpage):
        _translate = QtCore.QCoreApplication.translate
        mainpage.setWindowTitle(_translate("mainpage", "MainWindow"))
        self.intro_nav.setText(_translate("mainpage", "Introduction"))
        self.studyplan_nav.setText(_translate("mainpage", "Study Plan"))
        self.calender_nav.setText(_translate("mainpage", "Calendar"))
        self.stats_nav.setText(_translate("mainpage", "Statistics"))
        self.faq_nav.setText(_translate("mainpage", "FAQ\'s"))
        self.about_nav.setText(_translate("mainpage", "About "))
        self.contact_nav.setText(_translate("mainpage", "Contact"))
        self.quick_notes_title.setText(_translate("mainpage", "Notes"))
        self.todo_title.setText(_translate("mainpage", "To-do"))
        self.welcome_title.setText(_translate("mainpage", "Welcome"))
        self.note_1.setPlaceholderText(_translate("mainpage", "Enter note"))
        self.note_2.setPlaceholderText(_translate("mainpage", "Enter note"))
        self.note_3.setPlaceholderText(_translate("mainpage", "Enter note"))
        self.note_4.setPlaceholderText(_translate("mainpage", "Enter note"))
        self.last_update_1.setText(_translate("mainpage", "5 days ago"))
        self.last_update_2.setText(_translate("mainpage", "6 days ago"))
        self.last_update_3.setText(_translate("mainpage", "a few minutes ago"))
        self.last_update_4.setText(_translate("mainpage", "5 hours ago"))
        self.view_more_notes.setText(_translate("mainpage", "View more "))
        self.ai_chat_input.setPlaceholderText(_translate("mainpage", "Enter something ..."))

    def timer_clicked(self, event):
        # Pop up the timer dialog
        timer_dialog = QDialog()
        ui = Ui_Timer(timer_dialog)  # Pass timer_dialog object
        ui.setupUi(timer_dialog)
        ui.set_opacity(0.8)  # Set the opacity to 80%
        timer_dialog.exec_()
        timer_dialog.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Windows")
    mainpage = QtWidgets.QMainWindow()
    ui = Ui_mainpage()
    ui.setupUi(mainpage)
    mainpage.show()
    sys.exit(app.exec_())